### ISSUE TITLE
Sequelize 5 changes some configs of pool connection

### ISSUE THREAD

**Issue by buihongduc132** [d-band/koa-orm#53]
Sequelize v3 is using
```  
pool: {
    maxConnections: 10,
    minConnections: 0,
    maxIdleTime: 30000
  }
```

But v4 and v5 is changed into this
```
  pool: {
    max: 5,
    min: 0,
    acquire: 30000,
    idle: 10000
  }
```

So, old configs params will not works if upgrade to v4, v5.

**Comment by helloyou2012** [comment]
@buihongduc132 thx, we have change the config of the test and readme file.
