### ISSUE TITLE
DeprecationWarning: String based operators are deprecated. 

### ISSUE THREAD

**Issue by GKennyKwok** [d-band/koa-orm#55]
I use "sequelize": "^6.3.5",

But a warning appears

(node:3876) [SEQUELIZE0003] DeprecationWarning: String based operators are deprecated. Please use Symbol based operators for better security, read more at https://sequelize.org/master/manual/querying.html#operators

**Comment by helloyou2012** [comment]
@GKennyKwok thanks, it has been fixed at `koa-orm@3.2.0`. https://github.com/d-band/koa-orm/commit/463ee8373758d8d6d4ac3e586c7782e1b1875f95
